test = {   'name': 'challenge',
    'points': 4,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(pounds_to_newtons, float) and isinstance(mars, float) and isinstance(jupiter, float)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> abs(pounds_to_newtons - 444.52) < 4\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> abs(mars - 136.0776) < 2\nTrue', 'hidden': True, 'locked': False},
                                   {'code': '>>> abs(jupiter - 1124.90816) < 10\nTrue', 'hidden': True, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
